"""
Somatotype Bias Correction Module (S5_g0.25)
=============================================

Implements the S5_g0.25 correction strategy validated in Research V3 Phases 37-53b:
  - BayesianRidge multivariate correction for Endomorphy and Mesomorphy
  - Gap Restore (gamma=0.25) for mild variance preservation
  - Ectomorphy kept as-is (HWR-derived, already accurate)

Phase 51 findings (retrained G13/G38 + S5):
  - S5_g0.25 achieves 76.7% at T=1.75, 80.0% at T=2.0
  - Best balance: 100% Central + Ectomorph + Endo-Meso at T=1.75
  - Meso variance ratio 0.913 (closest to GT among all gamma values)

Phase 53b findings (fully nested LOOCV, zero data leakage):
  - S5_g0.25: 76.7% at T=1.75, 80.0% at T=2.0 (ZERO inflation from G13/G38 leakage)
  - G13/G38 baseline (nested): 66.7% at T=1.75 (S5 adds +10.0pp honest improvement)
  - All accuracy claims validated under fully honest evaluation

The BayesianRidge correction model uses [raw_endo, raw_meso, raw_ecto] as features
(3 components). Gap restore then rescales the Endo-Meso gap to preserve variance.

Usage:
    corrector = SomatotypeBiasCorrector()
    corrector.load_models()
    corrected_endo, corrected_meso, corrected_ecto = corrector.correct(endo, meso, ecto)
"""

import os
import pickle
import json
import numpy as np
from sklearn.linear_model import BayesianRidge

MODEL_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'ml_models')


# Production operating parameters (Phase 51: gamma updated from 0.5 to 0.25)
OPERATING_THRESHOLD = 1.75
GAMMA = 0.25


class SomatotypeBiasCorrector:
    """
    Applies S5_g0.25 bias correction to raw somatotype components.
    
    The correction has two stages:
    1. BayesianRidge regression: Maps [raw_endo, raw_meso, raw_ecto]
       to corrected Endomorphy and Mesomorphy independently
    2. Gap Restore (gamma=0.25): Rescales the Endo-Meso gap partially toward GT variance
    
    Pre-trained models must be generated by the training script before use.
    """
    
    # BayesianRidge hyperparameters (Phase 43-46: all 9 BR models use consistent priors)
    BR_PARAMS = dict(alpha_1=1e-2, alpha_2=1e-2, lambda_1=1e-2, lambda_2=1e-2)
    
    def __init__(self):
        self.endo_model = None   # BayesianRidge for Endomorphy
        self.meso_model = None   # BayesianRidge for Mesomorphy
        self.gap_params = {}     # gt_mean_gap, gt_gap_std, pred_gap_mean, pred_gap_std
        self.is_loaded = False
    
    def load_models(self, model_dir=None):
        """Load pre-trained S5 correction models."""
        if model_dir is None:
            model_dir = MODEL_DIR
        
        endo_path = os.path.join(model_dir, 's5_endo_correction.pkl')
        meso_path = os.path.join(model_dir, 's5_meso_correction.pkl')
        gap_path = os.path.join(model_dir, 's5_gap_params.json')
        
        with open(endo_path, 'rb') as f:
            self.endo_model = pickle.load(f)
        with open(meso_path, 'rb') as f:
            self.meso_model = pickle.load(f)
        with open(gap_path, 'r') as f:
            self.gap_params = json.load(f)
        
        self.is_loaded = True
        print(f"  S5_g0.25 correction models loaded")
        print(f"    Gap params: gt_std={self.gap_params['gt_gap_std']:.3f}, "
              f"pred_mean_gap={self.gap_params['pred_gap_mean']:.3f}, "
              f"pred_gap_std={self.gap_params['pred_gap_std']:.3f}, gamma={GAMMA}")
    
    def correct(self, endo, meso, ecto):
        """
        Apply S5_g0.25 correction to predicted somatotype components.
        
        Uses ONLY the 3 raw somatotype components as features (matching Phase 42's
        approach where X = [raw_endo, raw_meso, raw_ecto]).
        
        Args:
            endo: float - Raw predicted endomorphy (after G13/G38 calibration)
            meso: float - Raw predicted mesomorphy (after G13/G38 calibration)
            ecto: float - Raw predicted ectomorphy (after G13/G38 calibration)
            
        Returns:
            tuple: (corrected_endo, corrected_meso, corrected_ecto)
        """
        if not self.is_loaded:
            self.load_models()
        
        # Step 1: BayesianRidge correction using 3-component feature vector
        X = np.array([[endo, meso, ecto]])
        br_endo = self.endo_model.predict(X)[0]
        br_meso = self.meso_model.predict(X)[0]
        
        # Step 2: Gap Restore (gamma=0.25)
        # Matches Phase 51 formula:
        # new_gap = pred_gap_mean_tr + GAMMA * (gt_gap_std / pred_gap_std) * (pred_gap - pred_gap_mean_tr)
        pred_gap = br_endo - br_meso
        pred_mean = (br_endo + br_meso) / 2.0
        
        pred_gap_mean = self.gap_params['pred_gap_mean']
        gt_gap_std = self.gap_params['gt_gap_std']
        pred_gap_std = self.gap_params['pred_gap_std']
        
        new_gap = pred_gap_mean + GAMMA * (gt_gap_std / pred_gap_std) * (pred_gap - pred_gap_mean)
        
        final_endo = pred_mean + new_gap / 2.0
        final_meso = pred_mean - new_gap / 2.0
        
        # Ectomorphy is kept as-is (HWR-derived, no correction needed)
        final_ecto = ecto
        
        # Floor at 0.1
        final_endo = max(final_endo, 0.1)
        final_meso = max(final_meso, 0.1)
        final_ecto = max(final_ecto, 0.1)
        
        return round(final_endo, 1), round(final_meso, 1), round(final_ecto, 1)
