"""add measurements

Revision ID: 24ec57640eb0
Revises: 39beeabb558b
Create Date: 2026-02-01 12:00:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24ec57640eb0'
down_revision: Union[str, Sequence[str], None] = '39beeabb558b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('front_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('side_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('somatotype_endo', sa.Float(), nullable=True),
    sa.Column('somatotype_meso', sa.Float(), nullable=True),
    sa.Column('somatotype_ecto', sa.Float(), nullable=True),
    sa.Column('somatotype_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('circumferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_user_id'), 'measurement', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurement_user_id'), table_name='measurement')
    op.drop_table('measurement')
    # ### end Alembic commands ###
