"""add_recommendation_model

Revision ID: 981581734b2c
Revises: a1b2c3d4e5f6
Create Date: 2026-02-08 21:01:46.888309+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '981581734b2c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('measurement', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), server_default='Untitled Measurement', nullable=True))


def downgrade() -> None:
    op.drop_column('measurement', 'name')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
