"""Add deleted_at field

Revision ID: bc35073fd37a
Revises: 981581734b2c
Create Date: 2026-02-10 22:35:20.983125+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc35073fd37a'
down_revision: Union[str, Sequence[str], None] = '981581734b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at')
    op.drop_column('measurement', 'deleted_at')
    # ### end Alembic commands ###
